adx_calendar_enabled: false
adx_calendar_initialview: 756150001
adx_calendar_style: 756150000
adx_calendar_timezonemode: 756150000
adx_entitylistid: f8fab778-65d0-4453-b813-cfcba57253e1
adx_entityname: mshied_grantapplicant
adx_entitypermissionsenabled: true
adx_filter_enabled: false
adx_filterportaluser: mshied_applicant
adx_idquerystringparametername: id
adx_map_distanceunits: 756150001
adx_map_distancevalues: 5,10,25,50,100
adx_map_enabled: false
adx_map_infoboxoffsetx: 25
adx_map_infoboxoffsety: 46
adx_map_pushpinheight: 39
adx_map_pushpinwidth: 32
adx_map_resturl: https://dev.virtualearth.net/REST/v1/Locations
adx_map_type: 756150000
adx_map_zoom: 12
adx_name: Higher Ed - My Grant Applications
adx_odata_enabled: false
adx_pagesize: 10
adx_searchenabled: false
adx_view: 56185e45-6e5b-ed11-9561-000d3a3ac0ab
adx_views: >-
  {

    "Type": "ViewMetadata",

    "Views": [

      {

        "Type": "View",

        "ViewId": "56185e45-6e5b-ed11-9561-000d3a3ac0ab",

        "DisplayName": [

          {

            "Type": "LanguageResources",

            "LCID": 1033,

            "Value": ""

          }

        ]

      }

    ]

  }
