adx_contentdisposition: 756150000
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: Config.js
adx_parentpageid: 0fe71b62-1a91-450f-9ad0-8ea5b2344772
adx_partialurl: Config.js
adx_publishingstateid: 3a82fe40-8b07-46c0-95c4-b131b894acbe
adx_webfileid: 3f6ed68f-c49e-43dc-be50-266ffe447bdd
annotationid: 62fa1fc9-5b88-4d43-9bba-c148ee51433e
filename: Config.js
isdocument: true
mimetype: application/javascript
objectid: 3f6ed68f-c49e-43dc-be50-266ffe447bdd
objecttypecode: adx_webfile
