adx_contentdisposition: 756150000
adx_displayorder: 9
adx_enabletracking: false
adx_excludefromsearch: true
adx_hiddenfromsitemap: true
adx_name: Product B.png
adx_parentpageid: 0fe71b62-1a91-450f-9ad0-8ea5b2344772
adx_partialurl: Product B.png
adx_webfileid: f3441be7-1d33-40ac-96ad-deed3ca3dcde
annotationid: 3d0de840-83b2-493a-b42a-cdd457c72ca1
filename: Product B.png
isdocument: true
mimetype: image/png
objectid: f3441be7-1d33-40ac-96ad-deed3ca3dcde
objecttypecode: adx_webfile
